(function() {var implementors = {};
implementors['libffi_sys'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libffi_sys/struct._ffi_type.html' title='libffi_sys::_ffi_type'>_ffi_type</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libffi_sys/struct.ffi_cif.html' title='libffi_sys::ffi_cif'>ffi_cif</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libffi_sys/struct.ffi_raw.html' title='libffi_sys::ffi_raw'>ffi_raw</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libffi_sys/struct.ffi_closure.html' title='libffi_sys::ffi_closure'>ffi_closure</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libffi_sys/struct.ffi_raw_closure.html' title='libffi_sys::ffi_raw_closure'>ffi_raw_closure</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libffi_sys/struct.ffi_java_raw_closure.html' title='libffi_sys::ffi_java_raw_closure'>ffi_java_raw_closure</a>",];implementors['libffi'] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libffi/middle/struct.Builder.html' title='libffi::middle::Builder'>Builder</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libffi/low/struct.ffi_type.html' title='libffi::low::ffi_type'>_ffi_type</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libffi/low/struct.ffi_cif.html' title='libffi::low::ffi_cif'>ffi_cif</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='libffi/low/struct.ffi_closure.html' title='libffi::low::ffi_closure'>ffi_closure</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
